import fontPeyda from "@/constants/localFont";
import "./globals.css";
import Header from "@/components/header/Header";

export const metadata = {
  title: "MedadUi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${fontPeyda.variable} font-sans container px-4 m-auto`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
